services:
  - type: web
    name: my-streamlit-app
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: streamlit run app.py --server.port $PORT
    autoDeploy: true

