services:
  - type: web
    name: my-streamlit-app
    env: python
    startCommand: streamlit run ATFEH_Rana_5_code_final_092024.py --server.port $PORT
    plan: free
    autoDeploy: true

  - type: web
    name: my-flask-api
    env: python
    startCommand: gunicorn api:app --bind 0.0.0.0:$PORT  
    plan: free
    autoDeploy: true
